export default {
  //首页列表
  initMovieHomePageList(state,data){
    state.MovieHomePageList=data;
  },
  //频道列表
  initMovieChannelList(state,data){
    state.MovieChannelList=data;
  },
  //类型列表
  initMovieChannelTypeList(state,data){
    state.MovieChannelTypeList=data;
  },
  //系列列表
  initMovieSeriesList(state,data){
    state.MovieSeriesList=data;
  },
  //电影详情
  initMovieListDetail(state,data){
    state.MovieListDetail=data;
  }
}
