export default {
  //loading设置
  showLoading(state) {
    state.isLoading = true;
  },
  hideLoading(state) {
    state.isLoading = false;
  },
  //首页列表
  initMovieHomePageList(state,data){
    state.MovieHomePageList=data;
  },
  //首页轮播
  MoviesHuffling(state,data){
    state.MoviesHuffling=data;
  },
  //频道列表
  initMovieChannelList(state,data){
    state.MovieChannelList=data;
  },
  //类型列表
  initMovieChannelTypeList(state,data){
    state.MovieChannelTypeList=data;
  },
  //当前类型电影数
  initMovieChannelTypeListNum(state,data){
    state.MovieChannelTypeListNum=data;
  },
  //类型名
  initMovieChannelTypeObj(state,data){
    state.MovieChannelTypeObj=data;
  },
  //系列列表
  initMovieSeriesList(state,data){
    state.MovieSeriesList=data;
  },
  //电影详情
  initMovieListDetail(state,data){
    state.MovieListDetail=data;
  },
  //电影详情评分
  AddOrUpdateMovieListDetailRate(state,data){
    state.MovieListDetailRate=data;
  },
  //查询评论
  initMovieDetailComment(state,data){
    state.MovieDetailComment=data;
  },
  //评分
  initMovieListRate(state,data){
    state.MovieListRate=data;
  },
  //查询点赞
  initMovieDetailPointGood(state,data){
    state.MovieDetailPointGood=data;
  },
  //系列视频内容
  initMovieSeriesContList(state,data){
    state.MovieSeriesContList=data;
  },
  //系列视频集数Data
  initMovieSeriesNumHover(state,data){
    state.MovieSeriesNumHover=data;
  },
  //系列视频集数内容
  MovieSeriesContDetail(state,data){
    state.MovieSeriesContDetail=data;
  }
}
